# Generated by Django 4.1.5 on 2023-01-16 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_follow_followed_remove_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following_to',
        ),
        migrations.AddField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
